### ISSUE TITLE
branch command: teamwork urls are sometimes paths and sometimes fragments

### ISSUE THREAD

**Issue by ctorgalson** [Annertech/annertech-ddev#18]
Teamwork may display URLs using a path, _or_ a fragment, e.g. it considers both of these valid URLs:

- **path**: https://projects.YOURCOMPANY.com/app/tasks/17458364
- **fragment**: https://projects.YOURCOMPANY.com/#/tasks/17458364

The branch command only considers the path, which means the second URL errors because the _path_ is `/` (the _fragment_ is `/tasks/17458364`).

**Comment by bserem** [comment]
Thanks!
