### ISSUE TITLE
Consider removing "ddev-get" topic from repo

### ISSUE THREAD

**Issue by rfay** [Annertech/annertech-ddev#28]
It looks like this may be a bit of a "private" add-on with very specific audience.

Also the tests have been failing recently.

If it's not intended for general users, would you mind removing the "ddev-get" topic from it so it's less discoverable by the general public?

Thanks!
-Randy

**Comment by bserem** [comment]
@3mkay can you please have a look at this? I do not have enough permissions.

@rfay it is not intended to be closed, anyone can use it and I'd be delighted if people copy aspects of it for their own daily lives. That said, it is probably not something that others would use unless they read about it. The topic must be removed.

Thanks for pointing this out!

**Comment by 3mkay** [comment]
Topic removed.

**Comment by rfay** [comment]
Thanks, please consider getting the tests going too. I thought it was unattended because of the tests.

**Comment by bserem** [comment]
@rfay tests are now working. Thanks for the gentle push towards that direction and excuse me for taking so long to get them done.

**Comment by rfay** [comment]
thanks so much, sorry to pester you!

**Comment by bserem** [comment]
by all means, it had to be done!
