### ISSUE TITLE
Bash interpreter breaks on nixos

### ISSUE THREAD

**Issue by 3mkay** [Annertech/annertech-ddev#6]
https://github.com/Annertech/annertech-ddev/blob/e5dd2449c98abdf35bcd6b7dab28c499efaced03/scripts/git-hooks/commit-msg#L1

Does this script _need_ to use `bash` rather than `sh` like the others do? If it does can we use the env settings rather than force the path? Nothing can be committed when this addon is installed on our Nixsal boxes at the moment.

i.e. Use
`#!/usr/bin/env bash`

**Comment by bserem** [comment]
I don't have access to nixsal, but you can easily test it out.

Edit `.git/hooks/commit-msg` to your liking, verify it works.
In short, I highly doubt it needs `bash`, if it relies on bash now we will port it to `sh`

**Comment by bserem** [comment]
In the meanwhile I'll try to use it with `sh` locally

**Comment by bserem** [comment]
v1.0 uses env in shebang

Thanks for the hint, I was unaware of it.
